/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.meituan.td.service;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-08-02")
public class GetStudentResponse implements org.apache.thrift.TBase<GetStudentResponse, GetStudentResponse._Fields>, java.io.Serializable, Cloneable, Comparable<GetStudentResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetStudentResponse");

  private static final org.apache.thrift.protocol.TField STUDENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("students", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GetStudentResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GetStudentResponseTupleSchemeFactory());
  }

  public List<Student> students; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STUDENTS((short)1, "students");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STUDENTS
          return STUDENTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STUDENTS, new org.apache.thrift.meta_data.FieldMetaData("students", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Student.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetStudentResponse.class, metaDataMap);
  }

  public GetStudentResponse() {
  }

  public GetStudentResponse(
    List<Student> students)
  {
    this();
    this.students = students;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetStudentResponse(GetStudentResponse other) {
    if (other.isSetStudents()) {
      List<Student> __this__students = new ArrayList<Student>(other.students.size());
      for (Student other_element : other.students) {
        __this__students.add(new Student(other_element));
      }
      this.students = __this__students;
    }
  }

  public GetStudentResponse deepCopy() {
    return new GetStudentResponse(this);
  }

  @Override
  public void clear() {
    this.students = null;
  }

  public int getStudentsSize() {
    return (this.students == null) ? 0 : this.students.size();
  }

  public java.util.Iterator<Student> getStudentsIterator() {
    return (this.students == null) ? null : this.students.iterator();
  }

  public void addToStudents(Student elem) {
    if (this.students == null) {
      this.students = new ArrayList<Student>();
    }
    this.students.add(elem);
  }

  public List<Student> getStudents() {
    return this.students;
  }

  public GetStudentResponse setStudents(List<Student> students) {
    this.students = students;
    return this;
  }

  public void unsetStudents() {
    this.students = null;
  }

  /** Returns true if field students is set (has been assigned a value) and false otherwise */
  public boolean isSetStudents() {
    return this.students != null;
  }

  public void setStudentsIsSet(boolean value) {
    if (!value) {
      this.students = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STUDENTS:
      if (value == null) {
        unsetStudents();
      } else {
        setStudents((List<Student>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STUDENTS:
      return getStudents();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STUDENTS:
      return isSetStudents();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GetStudentResponse)
      return this.equals((GetStudentResponse)that);
    return false;
  }

  public boolean equals(GetStudentResponse that) {
    if (that == null)
      return false;

    boolean this_present_students = true && this.isSetStudents();
    boolean that_present_students = true && that.isSetStudents();
    if (this_present_students || that_present_students) {
      if (!(this_present_students && that_present_students))
        return false;
      if (!this.students.equals(that.students))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_students = true && (isSetStudents());
    list.add(present_students);
    if (present_students)
      list.add(students);

    return list.hashCode();
  }

  @Override
  public int compareTo(GetStudentResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStudents()).compareTo(other.isSetStudents());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStudents()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.students, other.students);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GetStudentResponse(");
    boolean first = true;

    sb.append("students:");
    if (this.students == null) {
      sb.append("null");
    } else {
      sb.append(this.students);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetStudentResponseStandardSchemeFactory implements SchemeFactory {
    public GetStudentResponseStandardScheme getScheme() {
      return new GetStudentResponseStandardScheme();
    }
  }

  private static class GetStudentResponseStandardScheme extends StandardScheme<GetStudentResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetStudentResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STUDENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.students = new ArrayList<Student>(_list0.size);
                Student _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new Student();
                  _elem1.read(iprot);
                  struct.students.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setStudentsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetStudentResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.students != null) {
        oprot.writeFieldBegin(STUDENTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.students.size()));
          for (Student _iter3 : struct.students)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetStudentResponseTupleSchemeFactory implements SchemeFactory {
    public GetStudentResponseTupleScheme getScheme() {
      return new GetStudentResponseTupleScheme();
    }
  }

  private static class GetStudentResponseTupleScheme extends TupleScheme<GetStudentResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetStudentResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStudents()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetStudents()) {
        {
          oprot.writeI32(struct.students.size());
          for (Student _iter4 : struct.students)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetStudentResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.students = new ArrayList<Student>(_list5.size);
          Student _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new Student();
            _elem6.read(iprot);
            struct.students.add(_elem6);
          }
        }
        struct.setStudentsIsSet(true);
      }
    }
  }

}

